/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as PagesIndexImport } from './routes/pages.index'
import { Route as PagesPageIdImport } from './routes/pages.$pageId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PagesIndexRoute = PagesIndexImport.update({
  id: '/pages/',
  path: '/pages/',
  getParentRoute: () => rootRoute,
} as any)

const PagesPageIdRoute = PagesPageIdImport.update({
  id: '/pages/$pageId',
  path: '/pages/$pageId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/pages/$pageId': {
      id: '/pages/$pageId'
      path: '/pages/$pageId'
      fullPath: '/pages/$pageId'
      preLoaderRoute: typeof PagesPageIdImport
      parentRoute: typeof rootRoute
    }
    '/pages/': {
      id: '/pages/'
      path: '/pages'
      fullPath: '/pages'
      preLoaderRoute: typeof PagesIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/pages': typeof PagesIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/pages': typeof PagesIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/pages/$pageId': typeof PagesPageIdRoute
  '/pages/': typeof PagesIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/pages/$pageId' | '/pages'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/pages/$pageId' | '/pages'
  id: '__root__' | '/' | '/pages/$pageId' | '/pages/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PagesPageIdRoute: typeof PagesPageIdRoute
  PagesIndexRoute: typeof PagesIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PagesPageIdRoute: PagesPageIdRoute,
  PagesIndexRoute: PagesIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/pages/$pageId",
        "/pages/"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/pages/$pageId": {
      "filePath": "pages.$pageId.tsx"
    },
    "/pages/": {
      "filePath": "pages.index.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
